CREATE TABLE public.data (
    id SERIAL PRIMARY KEY NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    image VARCHAR(255) NOT NULL
);

INSERT INTO public.data (name, description, image) VALUES ('Apple', 'Crunchy, juicy, with a sweet or tart flavor.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Banana', 'Creamy texture, rich in potassium and other nutrients.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Orange', 'Citrusy, refreshing, packed with vitamin C.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Mango', 'Sweet, tropical, with a smooth, creamy texture.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Strawberry', 'Juicy, vibrant, synonymous with summer.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Grape', 'Small, juicy, available in various colors and flavors.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Watermelon', 'Refreshing, hydrating, perfect for hot summer days.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Pineapple', 'Sweet, tangy, with a tropical aroma.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Kiwi', 'Tart, green flesh with edible seeds and fuzzy brown skin.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Blueberry', 'Small, sweet-tart, packed with antioxidants.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Peach', 'Juicy, fuzzy skin, deliciously fragrant.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Pear', 'Crisp, sweet, with a distinctive grainy texture.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Cherry', 'Juicy, sweet-tart, with a vibrant red hue.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Lemon', 'Tangy, acidic, versatile in cooking and beverages.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Raspberry', 'Tart-sweet, delicate, with tiny edible seeds.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Grapefruit', 'Tangy, slightly bitter, known for its pink flesh.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Papaya', 'Sweet, tropical, with orange flesh and black seeds.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Plum', 'Sweet, juicy, with a smooth skin and stone pit.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Coconut', 'Tropical, creamy, with a distinct coconut flavor.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Blackberry', 'Sweet-tart, juicy, and deeply colored.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Apricot', 'Sweet, fragrant, with velvety skin and a pit.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Avocado', 'Creamy, rich, technically a fruit due to its seed.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Fig', 'Sweet, chewy, with a unique texture and tiny seeds.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Cranberry', 'Tart, vibrant, often used in juices and sauces.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Lychee', 'Sweet, floral, with a translucent white flesh.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Passionfruit', 'Tangy-sweet, aromatic, with edible seeds.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Mango', 'Sweet, tropical, with a smooth, creamy texture.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Guava', 'Tropical, fragrant, with a pink or yellow flesh.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Persimmon', 'Sweet, tangy, with a firm texture when ripe.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Dragonfruit', 'Mildly sweet, visually striking with pink flesh and black seeds.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Tangerine', 'Sweet, citrusy, easy to peel and segment.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Cantaloupe', 'Sweet, juicy, with orange flesh and green rind.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Pomegranate', 'Tangy-sweet, with juicy arils containing seeds.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Jackfruit', 'Sweet, tropical, with a fibrous texture.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Elderberry', 'Tart, deep purple, rich in antioxidants.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Starfruit', 'Sweet-tart, with a star-shaped cross-section.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Nectarine', 'Juicy, smooth-skinned, similar to peach but without fuzz.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Mulberry', 'Sweet-tart, small, and packed with nutrients.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Kiwano', 'Also known as horned melon, with a unique spiky appearance and mild flavor.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Kumquat', 'Tiny, oval citrus fruits, eaten whole, skin and all.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Pomelo', 'Mildly sweet, similar to grapefruit but milder.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Lychee', 'Sweet, floral, with a translucent white flesh.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Longan', 'Sweet, similar to lychee but smaller.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Huckleberry', 'Sweet-tart, small, often used in pies and jams.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Boysenberry', 'Sweet-tart, a cross between raspberry, blackberry, and loganberry.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Cloudberry', 'Tart-sweet, with a delicate flavor, native to colder climates.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Miracle Fruit', 'Small, red berry that alters taste perception, making sour foods taste sweet.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Soursop', 'Sweet, tangy, with creamy flesh and spiky skin.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Feijoa', 'Also known as pineapple guava, with a sweet, aromatic flavor.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Breadfruit', 'Starchy, similar to potato when cooked.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Feijoa', 'Also known as pineapple guava, with a sweet, aromatic flavor.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Breadfruit', 'Starchy, similar to potato when cooked.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Ackee', 'Tropical fruit with creamy flesh, native to West Africa.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Bael', 'Sweet, aromatic, used in traditional medicine and culinary applications.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Salak', 'Also known as snake fruit, with a tangy-sweet flavor and scaly skin.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Rambutan', 'Sweet, juicy, with a hairy exterior and translucent flesh.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Mangosteen', 'Sweet-tart, with a soft, white flesh and thick, purple rind.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Jabuticaba', 'Unique fruit that grows directly on the trunk of the tree.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Carambola', 'Also known as starfruit, with a tangy-sweet flavor and star-shaped cross-section.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Pitaya', 'Also known as dragon fruit, with a mild, subtly sweet flavor.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Quince', 'Tart, astringent, often cooked into preserves and jellies.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Custard Apple', 'Sweet, creamy, with a custard-like texture.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Jujube', 'Sweet, crisp, with a flavor reminiscent of apples.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Ugli Fruit', 'Citrus fruit with a wrinkled, greenish-yellow skin and sweet-tart flavor.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Tamarillo', 'Egg-shaped fruit with a tangy-sweet flavor, also known as tree tomato.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Durian', 'Known for its pungent aroma and custard-like texture, with a complex flavor profile.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Buddhas Hand', 'Citrus fruit with segmented finger-like sections, used for its aromatic zest.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Miracle Berry', 'Small, red berry that alters taste perception, making sour foods taste sweet.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Cupuaçu', 'Sweet, creamy fruit with a flavor reminiscent of chocolate and pineapple.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Saskatoon Berry', 'Sweet, tart, similar to blueberries but with a nutty undertone.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('White Sapote', 'Sweet, creamy, with a custard-like texture and mild flavor.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Acerola', 'Tart, cherry-like fruit, known for its high vitamin C content.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Tamarind', 'Tangy-sweet, used in cooking, beverages, and candies.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Langsat', 'Sweet, tangy, with a translucent white flesh and thin skin.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Surinam Cherry', 'Sweet-tart, with a cherry-like flavor and edible skin.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Persimmon', 'Sweet, tangy, with a firm texture when ripe.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Currant', 'Tart-sweet berries, available in red, black, and white varieties.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Marionberry', 'Sweet-tart, a cross between blackberry and raspberry.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Loquat', 'Sweet, mildly tangy, with a smooth texture and seeds in the center.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('White Currant', 'Tart-sweet berries, similar to red currants but with a pale color.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Red Currant', 'Tart-sweet berries, bright red in color and packed with vitamin C.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Black Currant', 'Tart-sweet berries, dark purple to black in color and rich in antioxidants.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Cloudberry', 'Tart-sweet, with a delicate flavor, native to colder climates.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Loquat', 'Sweet, tangy, with a juicy flesh and smooth skin.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Jujube', 'Sweet, crisp, with a date-like flavor.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Acai', 'Nutrient-rich, with a deep purple color and tart flavor.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Acerola', 'Tart, cherry-like fruit, packed with vitamin C.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Bilberry', 'Small, dark-blue berries, similar to blueberries.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Barberry', 'Tart, small red berries used in culinary dishes.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Cloudberry', 'Tart-sweet, with a delicate flavor, native to colder climates.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Crabapple', 'Small, tart apples, often used in preserves and jams.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Damson Plum', 'Tart, purple plums, commonly used in cooking.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Elderberry', 'Tart, deep purple, rich in antioxidants.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Goji Berry', 'Sweet-tart, with a slightly chewy texture, and high in antioxidants.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Huckleberry', 'Sweet-tart, small berries, often used in pies and jams.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Juniper Berry', 'Small, blue-black berries used to flavor gin and meat dishes.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Lingonberry', 'Tart, red berries, often used in sauces and jams.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Marionberry', 'Sweet-tart, a cross between blackberry and raspberry.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Mulberry', 'Sweet-tart, small berries, rich in nutrients.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Durian', 'Known for its strong odor and custard-like texture.', '/missing.svg');
INSERT INTO public.data (name, description, image) VALUES ('Horned Melon', 'Also known as kiwano, with a spiky orange skin and green jelly-like flesh.', '/missing.svg');